[toolchain]
channel = "1.88.0"
components = [
    "cargo",
    "clippy",
    "llvm-tools",
    "rustfmt",
    "rust-analyzer",
    "rust-docs",
    "rust-std",
    "rust-src",
]
targets = [ "aarch64-unknown-none-softfloat" ]
