[package]
name = "kernel"
version = "0.1.0"
authors = ["Newton Ni <nwtnni@gmail.com>"]
edition = "2024"

[dependencies]
aarch64-cpu = "10.0"
arrayvec = { version = "0.7", default-features = false }
tock-registers = "0.9"
