[package]
name = "kernel"
version = "0.1.0"
authors = ["Newton Ni <nwtnni@gmail.com>"]
edition = "2024"

[dependencies]
aarch64-cpu.workspace = true
arrayvec.workspace = true
tock-registers.workspace = true
